### ISSUE TITLE
ReStartPolicy not work

### ISSUE THREAD

**Issue by jzp1025** [kubeflow/mxnet-operator#12]
While setting the Restartpolicy to Never , if I kill the pod (no matter what role it is) , the pod will still restart . Besides, if I kill the worker , the job will be still running incorrectly and actually it should be in state Failed .

**Comment by KingOnTheStar** [comment]
It seem like few persons will kill pod directly, instead if you want to stop the mxjob you should use `kubectl delete mxjob`.
Kill pod directly will sometime cause this problem because the mxjob-operator will inspect the status of scheduler, server, worker endlessly, if it doesn't find any pod of one of them, operator will start creating. And this action is won't be influenced by Restartpolicy. the mxjob will exit only when the job success or fail, however kill pod directly won't cause the mxjob be marked to fail now.
Unless the killing worker operation of you cause server or scheduler throw exception, the restart situation will happen.
I tested some case, the mxjob will stop correctly while you stop container by docker instead of kubectl or the process in the container throw exceptions.

**Comment by suleisl2000** [comment]
@KingOnTheStar Thank for your investigation. I agree with you that killing single pod directly via kubectl is not reasonable case here. I think we can close it since it is not a problem to me.
@jzp1025 What do you think about it?

**Comment by jzp1025** [comment]
RestartPolicy is for the pod which normally completed.
SGTM , we can close the issue
